;Configure file of FreeLayoutCreator
[Common]
Row=1
Column=2
ShowHideNote=0
ShowHideFooter=1
ShowHideScale=0
MaximizeWindow=1
XCoordinate=1
YCoordinate=0
Width=961
Height=913
DefaultPrinter=5
WindowLevel_S=256

; Define for Scale on Screen
Screen_CellSideToScale=5
Screen_ScaleUnit=1
Screen_MultipleUnit=5
Screen_AllMultiple=3
Screen_HighOfScaleUnit=10
Screen_HighOfScale=20
Screen_WidthOfScaleLine=1
Screen_BlackLineToWhiteLine=0
Screen_BlackLineRGB=0 0 0
Screen_WhiteLineRGB=255 255 255

; Define for Scale on Film
Print_CellSideToScale=10
Print_ScaleUnit=1
Print_MultipleUnit=5
Print_AllMultiple=3
Print_HighOfScaleUnit=20
Print_HighOfScale=40
Print_WidthOfScaleLine=2
Print_BlackLineToWhiteLine=0
Print_BlackLineRGB=0 0 0
Print_WhiteLineRGB=255 255 255

; Define for Crop and Zoom
MinCropSize=10
MaxZoomIn=10

;List of film size which is passed from Communicator to Creator
[FilmsizeSettingValue]
ValueNumber=6
Value0=1
Value1=2
Value2=8
Value3=16
Value4=32
Value5=64

;List of film size setting value (Unit: Inch)
[FilmSizeIn]
1=8INx10IN
2=10INx12IN
8=10INx14IN
16=14INx14IN
32=14INx17IN
64=11INx14IN

;List of film size setting value (Unit: Pixel)
[FilmSizePixel]
1=2000x2510
2=2506x3016
8=2540x3600
16=3520x3520
32=3520x4280
64=2540x3600
