[VistaRoot]
Ru=c:\Program Files\FujiFilm\FCR\Msg
ApplicationRoot=c:\Program files\FujiFilm\Hobbit
DataFolder=c:\ProgramData\FujiFilm\Hobbit\Data
UserFolder=c:\ProgramData\FujiFilm\Hobbit
UserFolder1=c:\ProgramData\FujiFilm\Hobbit
INet=c:\FCRWEB
WebHostName=(Local)
Jet=Microsoft.Jet.OLEDB.4.0
UserTempDir=UserTemp
LocalDataDir=LocalData
Image=\FujiFilm\Hobbit\Data\Image

[Root]
Ru=c:\Program Files\FujiFilm\FCR\Msg
ApplicationRoot=c:\Program files\FujiFilm\Hobbit
DataFolder=c:\Program files\FujiFilm\Hobbit\Data
UserFolder=c:\Documents and Settings\All Users\Application Data\FujiFilm\Hobbit
UserFolder1=c:\Program files\FujiFilm\Hobbit
INet=c:\FCRWEB
WebHostName=(Local)
Jet=Microsoft.Jet.OLEDB.4.0
UserTempDir=Temp
LocalDataDir=Data
Image=\Program files\FujiFilm\Hobbit\Data\Image

[String]
System=%ApplicationRoot%\System
Resource=%ApplicationRoot%\System\Resource
Bitmap=%ApplicationRoot%\System\Bmp
Temp=%UserFolder1%\Temp
Config=%UserFolder%\Config
Param=%UserFolder%\Param
EdrParam=%UserFolder1%\EdrParam
EdrParamBuiltin=%UserFolder1%\EdrParam\Builtin
EdrParamCassette=%UserFolder1%\EdrParam\Cassette
Log=%UserFolder%\Log
Job=%UserFolder1%\Job
UserTemp=%UserFolder%\%UserTempDir%
PDI=%UserFolder%\%LocalDataDir%\PDI
PDITemporary=%UserFolder%\%UserTempDir%\PDI
DICOMFileTemporary=%UserFolder%\%UserTempDir%\DICOMFile
Delivery=%UserFolder%\%UserTempDir%\DeliveryDownload
Output=%DataFolder%\Output
Update=%DataFolder%\Update
UserIconFolder=%DataFolder%\UserIcon
PDITemplate=%DataFolder%\PDITemplate
LocalImage=%UserFolder%\%LocalDataDir%\Image
OutputLog=%UserFolder%\Log\OutputLog
LUT=%UserFolder%\LUT
CrtLut=%UserFolder%\CrtLut
PaperPrintTemplateA4=%UserFolder1%\PaperPrint\Template\A4
ClientPaperPrint=%UserFolder%\%UserTempDir%\PaperPrint
CmdLog=%UserFolder%\Log\CmdLog
Backup=%DataFolder%\Backup
FFStdReceComTemp=%UserFolder1%\Receipt\Temp
EkarteTemp=%UserFolder%\Ekarte\Temp
NasMirroringSync=%UserFolder%\NasMirroring

ImportImageThumbnail=%UserFolder%\ImportImage\Thumbnail
ImportImageLock=%UserFolder%\ImportImage\Lock
ImportImageUpload=%UserFolder%\ImportImage\Upload
ImportECGTemp=%UserFolder%\ImportImage\ECG
ECGIcon=%DataFolder%\FEVFuji\ECG_Icon.jpg
MWMOnlineOrrgDDO=%DataFolder%\MWL 
MWMOnlineSearchDDO=%UserFolder%\Temp\MWL
MWMOnlineTempDDO=%UserFolder%\Temp\MWL
FreeLayoutTemp=%UserFolder%\%UserTempDir%\FreeLayoutPrintTemp
FreeLayoutRequest=%UserFolder%\%UserTempDir%\FreeLayoutPrintTemp\Request
Media=%UserFolder1%\Media
ConsoleOrder=%UserFolder%\Temp\ConsoleOrder

DcmOfflineUpload=%UserFolder%\%UserTempDir%\C2S
DcmOfflineWork=%UserFolder%\%UserTempDir%\DcmOffline\ClientWork
DICOMDIR=%UserFolder1%\Media\DICOMDIR
ExportMedia=%UserFolder1%\Media\Export
ImportMedia=%UserFolder1%\Media\Import
Schema=%UserFolder1%\Media\Schema
Duplicate=%UserFolder1%\Media\Duplicate

Retrieve=%UserFolder1%\Retrieve
RetrieveImportImage=%UserFolder1%\Retrieve\ImportImage
DicomImportData=%UserFolder1%\Retrieve\DicomImportData

Download=%INet%\Download
DivideImage=%INet%\Download\Image

RetrieveError=%DataFolder%\Error\Retrieve
ErrorDirectory=%DataFolder%\Error

SPMediaProcBat=%UserFolder1%\Temp\MediaProcDB\create_sp_mediaproc.bat
SPRtrvProcBat=%UserFolder1%\Temp\RtrvProcDB\create_sp_rtrvproc.bat

WebImageData=http://%WebHostName%/FCRWeb/Image
UserIcon=http://%WebHostName%/FCRWeb/UserIcon
StudyListURL=http://%WebHostName%/FCRWeb/StudyList/Main.aspx
ReserveListURL=http://%WebHostName%/FCRWeb/CrExam/MainCE.aspx

DBAccessBase=http://%WebHostName%/FCRWeb/FCRWebService/DBAccessBase.asmx?WSDL
DeliveryService=http://%WebHostName%/FCRWeb/FCRWebService/DeliveryService.asmx?WSDL
GeneralService=http://%WebHostName%/FCRWeb/FCRWebService/GeneralService.asmx?WSDL
MasterInfoService=http://%WebHostName%/FCRWeb/FCRWebService/MasterInfoService.asmx?WSDL
MediaService=http://%WebHostName%/FCRWeb/FCRWebService/MediaService.asmx?WSDL
StudyInfoService=http://%WebHostName%/FCRWeb/FCRWebService/StudyInfoService.asmx?WSDL
TransferFileService=http://%WebHostName%/FCRWeb/FCRWebService/TransferFileService.asmx?WSDL
CertificationService=http://%WebHostName%/FCRWeb/FCRWebService/CertificationService.asmx?WSDL
ImportImageService=http://%WebHostName%/FCRWeb/FCRWebService/ImportImageService.asmx?WSDL
PresetService=http://%WebHostName%/FCRWeb/FCRWebService/PresetInfoService.asmx?WSDL
WebInputImage=http://%WebHostName%/FCRWeb/Download/Image
ClientStartPage=http://%WebHostName%/FCRWeb/main.html

SQLPatientDB=Packet Size=4096;User Id=sa;Data Source=(local);Persist Security Info=False;Initial Catalog=Patient;Password=fcr-dms
SQLStudyDB=Packet Size=4096;User Id=sa;Data Source=(local);Persist Security Info=False;Initial Catalog=Study;Password=fcr-dms
SQLHistoryDB=Packet Size=4096;User Id=sa;Data Source=(local);Persist Security Info=False;Initial Catalog=History;Password=fcr-dms
SQLUserDB=Packet Size=4096;User Id=sa;Data Source=(local);Persist Security Info=False;Initial Catalog=UserData;Password=fcr-dms
SQLListConfigDB=Packet Size=4096;User Id=sa;Data Source=(local);Persist Security Info=False;Initial Catalog=ListConfig;Password=fcr-dms
SQLPresetDB=Packet Size=4096;User Id=sa;Data Source=(local);Persist Security Info=False;Initial Catalog=Preset;Password=fcr-dms
SQLExplanationDB=Packet Size=4096;User Id=sa;Data Source=(local);Persist Security Info=False;Initial Catalog=Explanation;Password=fcr-dms
StudyDB=Provider=SQLOLEDB.1;Persist Security Info=False;User ID=sa;pwd=fcr-dms;Initial Catalog=Study;Data Source=(Local)

MediaDirInfoDB=Provider=SQLOLEDB.1;Persist Security Info=False;User ID=sa;pwd=fcr-dms;Initial Catalog=Study;Data Source=(Local)
MediaProcDB=Provider=SQLOLEDB.1;Persist Security Info=False;User ID=sa;pwd=fcr-dms;Initial Catalog=tempdb;Data Source=(Local)
RtrvProcDB=Provider=SQLOLEDB.1;Persist Security Info=False;User ID=sa;pwd=fcr-dms;Initial Catalog=tempdb;Data Source=(Local)

SysMasterDB=Provider=%Jet%;Data Source=%UserFolder%\Config\SysMaster.mdb;Persist Security Info=False
SysMasterDBbak=Provider=%Jet%;Data Source=%UserFolder%\Config.bak\SysMaster.mdb;Persist Security Info=False
SysConfigDB=Provider=%Jet%;Data Source=%UserFolder%\Config\SysConfig.mdb;Persist Security Info=False
NetMasterDB=Provider=%Jet%;Data Source=%UserFolder%\Config\NetMaster.mdb;Persist Security Info=False
NetMasterDBbak=Provider=%Jet%;Data Source=%UserFolder%\Config.bak\NetMaster.mdb;Persist Security Info=False
NetConfigDB=Provider=%Jet%;Data Source=%UserFolder%\Config\NetConfig.mdb;Persist Security Info=False
PNDB=Provider=%Jet%;Data Source=%UserFolder%\Config\PN.mdb;Persist Security Info=False
PNDBbak=Provider=%Jet%;Data Source=%UserFolder%\Config.bak\PN.mdb;Persist Security Info=False
ImageOverlayDB=Provider=%Jet%;Data Source=%UserFolder%\Config\ImageOverlay.mdb;Persist Security Info=False
ImageOverlayDBbak=Provider=%Jet%;Data Source=%UserFolder%\Config.bak\ImageOverlay.mdb;Persist Security Info=False
DeleteListDB=Provider=%Jet%;Data Source=%UserFolder%\Config\DeleteList.mdb;Persist Security Info=False

LangStrDB=Provider=%Jet%;Data Source=%ApplicationRoot%\System\Resource\LangStr.mdb;Mode=13;Persist Security Info=False
LangMsgBoxDB=Provider=%Jet%;Data Source=%ApplicationRoot%\System\Resource\LangMsgBox.mdb;Mode=13;Persist Security Info=False

FFMainMsgDB=Provider=%Jet%;Data Source=%UserFolder%\Config\FFMainMsg.mdb;Persist Security Info=False
FFMainProcDB=Provider=%Jet%;Data Source=%UserFolder%\Config\FFMainProc.mdb;Persist Security Info=False

DicomPrCrDB=Provider=%Jet%;Data Source=%UserFolder%\Config\DicomPrCr.mdb;Persist Security Info=False
DicomPrintTagDB=Provider=%Jet%;Data Source=%UserFolder%\Config\DicomPrintTag.mdb;Persist Security Info=False
DicomStorageTagDB=Provider=%Jet%;Data Source=%UserFolder%\Config\DicomStorageTag.mdb;Persist Security Info=False

DepartDB=Provider=%Jet%;Data Source=%UserFolder%\Param\Depart.mdb;Persist Security Info=False
DepartDBbak=Provider=%Jet%;Data Source=%UserFolder%\Param.bak\Depart.mdb;Persist Security Info=False
DisplayDataDB=Provider=%Jet%;Data Source=%UserFolder%\Param\DisplayData.mdb;Persist Security Info=False
DisplayDataDBbak=Provider=%Jet%;Data Source=%UserFolder%\Param.bak\DisplayData.mdb;Persist Security Info=False
MenuDataDB=Provider=%Jet%;Data Source=%UserFolder%\Param\MenuData.mdb;Persist Security Info=False
MenuDataDBbak=Provider=%Jet%;Data Source=%UserFolder%\Param.bak\MenuData.mdb;Persist Security Info=False
ConsoleMenuDataDB=Provider=%Jet%;Data Source=%UserFolder%\Param\ConsoleMenuData.mdb;Persist Security Info=False
ConsoleDisplayDataDB=Provider=%Jet%;Data Source=%UserFolder%\Param\ConsoleDisplayData.mdb;Persist Security Info=False
ParamedicDB=Provider=%Jet%;Data Source=%UserFolder%\Param\Paramedic.mdb;Persist Security Info=False
ParamedicDBbak=Provider=%Jet%;Data Source=%UserFolder%\Param.bak\Paramedic.mdb;Persist Security Info=False

BcrDataFormatDB=Provider=%Jet%;Data Source=%UserFolder%\Param\BcrDataFormat.mdb;Persist Security Info=False
BcrDataFormatDBbak=Provider=%Jet%;Data Source=%UserFolder%\Param.bak\BcrDataFormat.mdb;Persist Security Info=False
FilmMarkDB=Provider=%Jet%;Data Source=%UserFolder%\Param\FilmMark.mdb;Persist Security Info=False
FilmMarkDBbak=Provider=%Jet%;Data Source=%UserFolder%\Param.bak\FilmMark.mdb;Persist Security Info=False
McrDataFormatDB=Provider=%Jet%;Data Source=%UserFolder%\Param\McrDataFormat.mdb;Persist Security Info=False
SelectorDB=Provider=%Jet%;Data Source=%UserFolder%\Param\Selector.mdb;Persist Security Info=False
SelectorDBbak=Provider=%Jet%;Data Source=%UserFolder%\Param.bak\Selector.mdb;Persist Security Info=False
XconParamDB=Provider=%Jet%;Data Source=%UserFolder%\Param\XconParam.mdb;Persist Security Info=False
XconParamDBbak=Provider=%Jet%;Data Source=%UserFolder%\Param.bak\XconParam.mdb;Persist Security Info=False
InputIDDB=Provider=%Jet%;Data Source=%UserFolder%\Param\InputID.mdb;Persist Security Info=False

RuStatusDataDB=Provider=%Jet%;Data Source=%Ru%\RuStr.mdb;Mode=13;Persist Security Info=False
RuErrorDataDB=Provider=%Jet%;Data Source=%Ru%\RuMsgBox.mdb;Mode=13;Persist Security Info=False

ReceiptConnectDB=Provider=%Jet%;Data Source=%UserFolder%\Config\ReceiptConnect.mdb;Persist Security Info=False

DeliverConfigIni=%ApplicationRoot%\System\DeliverConfig.ini
UserFileListIni=%ApplicationRoot%\System\UserFileList.ini

EkarteOrderTemp=%UserFolder%\Ekarte\OrderTemp

SystemMarkerFolder=%UserFolder%\SystemMarker
UserMarkerFolder=%UserFolder%\UserMarker

ClientLog=%UserFolder%\Log\CLIENT_LOG

#Å•Å•Å• HobbitV2.2(B) FFâúñÏ ADD
IIP_LocalImage=%UserFolder%\%LocalDataDir%\Image
IIP_Config=%UserFolder%\Config
IIP_Param=%UserFolder%\Param
IIP_CrtLut=%UserFolder%\Lut
#Å£Å£Å£ HobbitV2.2(B) FFâúñÏ ADD

#Å•Å•Å• HobbitV2.2(B) TYSä›ñ{ ADD
FormatInfoDB=Provider=%Jet%;Data Source=%ApplicationRoot%\System\FLC\FormatInfo.mdb;Persist Security Info=False
FormatInfoDBbak=Provider=%Jet%;Data Source=%UserFolder%\Config.bak\FormatInfo.mdb;Persist Security Info=False
#Å£Å£Å£ HobbitV2.2(B) TYSä›ñ{ ADD

#Å•Å•Å• HobbitV3.0(B) FFSíÜç™ ADD
ParamGPR=%UserFolder%\Param\ImageProcessing\ImageProc\System\DR\InDirFPD
#Å£Å£Å£ HobbitV3.0(B) FFSíÜç™ ADD
