@echo off
rem ///////////////////////////////////////////////////////////////////////////////
rem //
rem //  関数:  RestoreConfigFiles
rem //
rem //  目的:  この関数は、Configファイル類のリストアを行う
rem //         設定を引き継ぐファイルを*.bakディレクトリから正規のディレクトリに
rem //         コピーする。
rem //
rem //  ｺﾒﾝﾄ:  XCOPY実施時にファイルかディレクトリか問い合わせてくる場合があるため
rem //         先頭に「ECHO F」を付けて回避する。
rem //         そのためXCOPYコマンドはファイル単位で追加すること。
rem //
rem //  履歴:  2014/02/018 TYS岸本  V2.4(B)HF0007  Create new.
rem //
rem ///////////////////////////////////////////////////////////////////////////////

rem **************************************************************
rem ******    Check Operating System                        ******
rem **************************************************************
:CHECK_OPERATING_SYSTEM

for /f "tokens=1-3" %%i in ('ver') do set os=%%k
if "%os%"=="XP" (set PATH_HOBBIT_APPDATA=C:\Documents and Settings\All Users\Application Data\FujiFilm\Hobbit) else (set PATH_HOBBIT_APPDATA=C:\ProgramData\FujiFilm\Hobbit)
if "%os%"=="XP" (set PATH_HOBBIT_USRDATA=C:\Program Files\FujiFilm\Hobbit) else (set PATH_HOBBIT_USRDATA=C:\ProgramData\FujiFilm\Hobbit)

rem **************************************************************
rem ******    Set Application directory                     ******
rem **************************************************************
set PATH_HOBBIT_PROGRAM=C:\Program Files\FujiFilm\Hobbit


rem **************************************************************
rem ******    Restore config files                          ******
rem **************************************************************
SET SOURCE_PATH=%PATH_HOBBIT_APPDATA%\Config.bak\
SET DEST_PATH=%PATH_HOBBIT_APPDATA%\Config\

SET FILE_NAME=ClientInfo.ini
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=TagReplace.ini
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=TagLookup.ini
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=PDI_Institution.txt
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=DefaultSearchPanelSetting.xml
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

rem **************************************************************
rem ******    Restore parameter files                       ******
rem **************************************************************
SET SOURCE_PATH=%PATH_HOBBIT_APPDATA%\Param.bak\
SET DEST_PATH=%PATH_HOBBIT_APPDATA%\Param\

SET FILE_NAME=param.ini
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=PNTPRM.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Pntumn.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=EsSelect.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=EsSelu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=FNC.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Fncu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipeshg.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipeshgu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipeshp.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipeshpu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipesm.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipesmu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipesn.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipesnu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipesop.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipesopu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipestn.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HIPMENU.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HIPMNRL.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HIPOP.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HIPOPT.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipoptu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipopu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HIPSTD.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipstdu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hipumn.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HP.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hpg.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hpgu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HPT.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HptK4.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=HptK4u.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hptu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Hpu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=PEM.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=PEMT.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Pemtu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Pemu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=SELECT.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Selectu.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=ExposureIndex.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=EILimitParameter.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

rem **************************************************************
rem ******    Restore EDR Parameter files                   ******
rem **************************************************************
SET SOURCE_PATH=%PATH_HOBBIT_USRDATA%\EdrParam.bak\
SET DEST_PATH=%PATH_HOBBIT_USRDATA%\EdrParam\

SET FILE_NAME=irmprm.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=nnprm.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=irmumn.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=nnumn.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Builtin\mpmprm.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Builtin\mpmumn.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Cassette\mpmprm.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

SET FILE_NAME=Cassette\mpmumn.prm
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

rem **************************************************************
rem ******    Restore Free Layout Print config files        ******
rem **************************************************************
SET SOURCE_PATH=%PATH_HOBBIT_APPDATA%\Config.bak\
SET DEST_PATH=%PATH_HOBBIT_PROGRAM%\System\FLC\

SET FILE_NAME=FmtFooter.txt
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

rem **************************************************************
rem ******    Restore Free Draw config files                ******
rem **************************************************************
SET SOURCE_PATH=%PATH_HOBBIT_APPDATA%\Config.bak\
SET DEST_PATH=%PATH_HOBBIT_PROGRAM%\System\

SET FILE_NAME=FDDSettingInfo.ini
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))

rem **************************************************************
rem ******    Success restore                               ******
rem **************************************************************
:SUCCESS
EXIT 0

rem **************************************************************
rem ******    Failure restore                               ******
rem **************************************************************
:FAILURE
eventcreate /L Application /T ERROR /SO "RestoreConfigFiles" /ID "200" /D "[Failed restore] %FILE_NAME% : %ERRORLEVEL%"
EXIT 1


rem **************************************************************
rem ******    File copy                                     ******
rem **************************************************************
:FILE_COPY
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (ECHO F | XCOPY /Y /R "%SOURCE_PATH%%FILE_NAME%" "%DEST_PATH%%FILE_NAME%")
IF EXIST "%SOURCE_PATH%%FILE_NAME%" (IF %ERRORLEVEL% NEQ 0 (GOTO FAILURE))
EXIT /B 0
